### ISSUE TITLE
Dokku Host and Port Env Variables

### ISSUE THREAD

**Issue by AlJohri** [jlachowski/dokku-rabbitmq-plugin#1]
Is there any reason why the HOST and PORT and provided as ENV variables within linked container?

```
ubuntu@ip-xx-xxx-xx-xxx:/var/lib$ dokku rabbitmq:info dev

       Host: 172.17.0.5
       Gateway: 172.17.42.1
       Secret AMQP port: 5672
       Secret ADMIN port: 15672

ubuntu@ip-xx-xxx-xx-xxx:/var/lib$ dokku redis:info dev

       Host: 172.17.0.3
       Public port: 49154

ubuntu@ip-xx-xxx-xx-xxx:/var/lib$ dokku postgresql:info dev

       Host: 172.17.42.1
       Port: 49153
       User: 'root'
       Password: 'xxxxxxxx'
       Database: 'db'

       Url: 'postgres://root:xxxxxxxx@172.17.42.1:49153/db'

ubuntu@ip-xx-xxx-xx-xxx:/var/lib$ dokku config dev
=== dev config vars ===
BROKER_PASSWORD: xxxxxxxx
BROKER_PATH:     //
BROKER_SCHEME:   amqp
BROKER_USERNAME: admin
C_FORCE_ROOT:    true
DATABASE_URL:    postgres://root:xxxxxxxx@172.17.42.1:49153/db
HEROKU:          1
REDIS_URL:       redis://172.17.0.3:6379
```

**Comment by AlJohri** [comment]
@jlachowski you set the following config variables but don't set the Secret Port?

```
dokku config:set $APP "BROKER_SCHEME=amqp" "BROKER_USERNAME=admin" "BROKER_PASSWORD=$RABBITMQ_PASSWORD" "BROKER_PATH=//"
```

Can you explain why?

**Comment by jlachowski** [comment]
The port is already exported in ENV variables due to container linking (this is done by docker itself). This ensures that the port and IP are always up-to-date after rebuild of any container.

**Comment by AlJohri** [comment]
@jlachowski Can you explain how I can access it? 

What is the ENV variable called for the PORT and IP? Or could you point me to some documentation on the docker side?

I see these variables as of now

```
BROKER_PASSWORD: xxxxxxxx
BROKER_PATH:     //
BROKER_SCHEME:   amqp
```

which results in this:

``` shell
RABBITMQ_URL = "BROKER_SCHEME://$BROKER_USERNAME:$BROKER_PASSWORD@???HOST???:???PORT???$BROKER_PATH"
```

**Comment by jlachowski** [comment]
You can access it from the linked container via BROKER_PORT env variable (should be something like BROKER_PORT=tcp://172.17.0.8:1572).

More info about environment variables of link containers can be found here: http://docs.docker.io/en/latest/use/working_with_links_names/

**Comment by AlJohri** [comment]
@jlachowski thanks for the link. I'll try it out.

This commit on a fork does something similar to what I was referring to: https://github.com/Vincit/dokku-rabbitmq-plugin-singleinstance/commit/4ce3f867ded1d9d8e5795a9fc27bc897d89b6b4c

You say that `This ensures that the port and IP are always up-to-date after rebuild of any container.`

It seems similar plugins, Redis and Postgres take a different approach

Hardcode IP address: https://github.com/Kloadut/dokku-pg-plugin/blob/master/commands#L167
Get IP and port using docker inspect: https://github.com/luxifer/dokku-redis-plugin/blob/master/commands#L84

This allows for a cleaner interface with just DATABASE_URL or REDIS_URL.

Would you be interested in a PR that does something similar?

**Comment by jlachowski** [comment]
I have also postgresql, graphite and memcached plugins which use the same approach (as this plugin). The problem with the suggested approach is that you need to restart the app (e.g. django app) in order to reload new env settings in the app itself once you rebuild any of the related containers (e.g. postgresql, ... etc. update only the ENV variable) whereas the linking does it for you (it restarts the all linked containers). 

As I'm using it on a production environment I would prefer to stick with my solution (unless I'm 100% sure that the other will work as described above), but feel free to fork it and adjust to your needs.

**Comment by AlJohri** [comment]
That makes a lot of sense. Thanks for the explanation!

Would you be able to add your `postgresql` and `memcached` plugins to https://github.com/progrium/dokku/wiki/Plugins ? I see graphite is already there by name of `Graphite/statsd`.

Also I was looking at another redis plugin that requires the use of the dokku-link plugin. They create the REDIS_URL parameter using this

https://github.com/jezdez/dokku-redis-plugin/blob/master/commands#L108

Would this work in your approach?

**Comment by jlachowski** [comment]
This could work as it uses both solutions (container linking and ENV variable setting). Need to test it first though ;-).

**Comment by jlachowski** [comment]
This
